### ISSUE TITLE
[request] Move the 10-pages-long noisy introduction to the BOTTOM of the readme

### ISSUE THREAD

**Issue by heysokam** [LGUG2Z/helix-vim#31]
## Request
**Please reconsider moving the `Usage` section to the very top of the readme.**

## Reasoning TL;DR
I don't think the introduction is doing this repository any good.
I landed on this repository on four different occasions, and run away the other way every single time, dismissing helix as a viable editor altogether because of that.

This time I **forced** myself to go through the readme noise anyway, and turns out the only thing anyone should care about as an **introduction** is at the VERY BOTTOM of the damn explanation. Like, what?

## UX problem statement
Consider this UX situation _(which is exactly what I went through myself)_:

### Step 0
I just landed on this repo. I know nothing about it.
At this point in my user journey, while I'm being introduced to the repo... I don't care about your opinions. AT ALL.  
**Yet**.
I'm not invested in what you created.
I might be in the future. But I know nothing about this yet.
I know nothing about this repo, how can I be!

### Step 3 or 4
This step shouldn't even be here. We haven't gone through step1 yet!

### Step 1
I read the `Usage` section.
Thanks to that, I know what the tool does.
I look around the repo.
I decide if I like what I see.
I realize that you have added some awesome comments on the file to explain the issues.
I understand the problem, and I understand how you solved it.

### Step 2
I install helix. I install your config. I look around. Holy crap, things work!
You solved the problem I had!
**Now** I care about what you have to say.

### Next step
I might (or might not) read your long ass story about your personal struggles.
I may also just go away, and come back to the story sometime in the future.
Or maybe I just read a bit, feel identified with parts, and nod in understanding.
Either way... this step is unnecessary to get my problem solved.

### Except
..... You forced me into the last step, as a first step!!
It just makes no sense.

## Frustating UX
And why am I writing this long ass explanation about the UX of the readme?

Because... turns out, this configuration file is what I have been searching for for months... and I dismissed helix as a good editor every-single-time because I couldn't even understand if this solved my problem.
And I really disagreed and disliked your "whiny" story. So I just cringed and run the other way.
I can empathize with parts of the problem statement, but definitely not with the emotions at all.

I'm not complaining about nvim like your story does. I don't care. At all.
I just want simplicity. That's it. And helix is simpler, but my muscle memory is too strong.
There is no complaining, but your story targets complaints and frustration very directly.
What if I'm not that person?

Anyway. I'll stop rambling.
This config is incredible, and it really solved my problem. I can finally use helix.
And I respect the way you present your story, just in case it wasn't clear.
You do you, I can respect that.

But please don't dismiss this criticism as "useless".
Because right now the UX of your readme introduction is losing users, and you don't even know they exist because they are not invested enough yet to care about your story.

## Solution
Literally just move the `Usage` section to the very top of the file.
That's it. Problem solved.

**Comment by LGUG2Z** [comment]
The "About" section of the README _is_ the repository.

The `config.toml` was always just an afterthought.

**Comment by heysokam** [comment]
![image](https://github.com/LGUG2Z/helix-vim/assets/7308253/9bfe486c-fb21-4b6b-a4ea-26dfa63e98b8)

@LGUG2Z Why are you accepting or applying changes to the `.toml` file at all then?
Anyway, I can see I pissed you off with my disagreements and honesty.
I just though honesty was more important than either of our opinions.
I apologize for that. Have a good day.
